package com.garmentstore.common.exception;
import com.garmentstore.common.response.*; import jakarta.servlet.http.HttpServletRequest; import org.springframework.http.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.authentication.BadCredentialsException; import org.springframework.web.bind.MethodArgumentNotValidException; import org.springframework.web.bind.annotation.*; import java.util.List;
@RestControllerAdvice public class GlobalExceptionHandler {
  @ExceptionHandler(BusinessException.class) public ResponseEntity<ApiResponse<Void>> handleBusiness(BusinessException ex,HttpServletRequest req){return ResponseEntity.status(ex.getStatus()).body(ApiResponse.failure(ex.getMessage(),new ErrorDetails(ex.getCode(),req.getRequestURI(),null)));}
  @ExceptionHandler(MethodArgumentNotValidException.class) public ResponseEntity<ApiResponse<Void>> handleValidation(MethodArgumentNotValidException ex,HttpServletRequest req){List<FieldErrorDetail> fields=ex.getBindingResult().getFieldErrors().stream().map(e->new FieldErrorDetail(e.getField(),e.getDefaultMessage())).toList();return ResponseEntity.badRequest().body(ApiResponse.failure("Validation failed",new ErrorDetails("VALIDATION_FAILED",req.getRequestURI(),fields)));}
  @ExceptionHandler(BadCredentialsException.class) public ResponseEntity<ApiResponse<Void>> handleBadCredentials(BadCredentialsException ex,HttpServletRequest req){return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(ApiResponse.failure("Invalid credentials",new ErrorDetails("INVALID_CREDENTIALS",req.getRequestURI(),null)));}
  @ExceptionHandler(AccessDeniedException.class) public ResponseEntity<ApiResponse<Void>> handleAccessDenied(AccessDeniedException ex,HttpServletRequest req){return ResponseEntity.status(HttpStatus.FORBIDDEN).body(ApiResponse.failure("Access denied",new ErrorDetails("ACCESS_DENIED",req.getRequestURI(),null)));}
  @ExceptionHandler(Exception.class) public ResponseEntity<ApiResponse<Void>> handleGeneric(Exception ex,HttpServletRequest req){return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ApiResponse.failure("Unexpected server error",new ErrorDetails("INTERNAL_SERVER_ERROR",req.getRequestURI(),null)));}
}
