create TABLE categories(id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,slug VARCHAR(180) NOT NULL UNIQUE,parent_category_id BIGINT NULL,display_order INT NOT NULL DEFAULT 0,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),CONSTRAINT fk_cat_parent FOREIGN KEY(parent_category_id) REFERENCES categories(id));
CREATE TABLE products(id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(200) NOT NULL,slug VARCHAR(220) NOT NULL UNIQUE,category_id BIGINT NOT NULL,gender_tag VARCHAR(30) NOT NULL,mrp DECIMAL(12,2) NOT NULL,selling_price DECIMAL(12,2) NOT NULL,discount_percent INT NOT NULL DEFAULT 0,color VARCHAR(80),description TEXT,fabric_details VARCHAR(500),care_instructions VARCHAR(500),country_of_origin VARCHAR(120),return_policy_enabled BOOLEAN NOT NULL DEFAULT TRUE,meta_title VARCHAR(200),meta_description VARCHAR(500),status VARCHAR(30) NOT NULL,created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),deleted_at TIMESTAMP(6),CONSTRAINT fk_prod_cat FOREIGN KEY(category_id) REFERENCES categories(id));
CREATE TABLE product_images(id BIGINT AUTO_INCREMENT PRIMARY KEY,product_id BIGINT NOT NULL,media_url VARCHAR(700) NOT NULL,display_order INT NOT NULL DEFAULT 0,is_thumbnail BOOLEAN NOT NULL DEFAULT FALSE,CONSTRAINT fk_img_prod FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE product_variants(id BIGINT AUTO_INCREMENT PRIMARY KEY,product_id BIGINT NOT NULL,size_code VARCHAR(30) NOT NULL,sku_code VARCHAR(120) NOT NULL UNIQUE,is_active BOOLEAN NOT NULL DEFAULT TRUE,CONSTRAINT fk_var_prod FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE featured_products(id BIGINT AUTO_INCREMENT PRIMARY KEY,product_id BIGINT NOT NULL,display_order INT NOT NULL DEFAULT 0,is_active BOOLEAN NOT NULL DEFAULT TRUE,CONSTRAINT fk_feat_prod FOREIGN KEY(product_id) REFERENCES products(id));
Update the featured_products table to include current timestamp & update timestamp or update the entity class -
for now - ALTER TABLE featured_products ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
          ALTER TABLE featured_products ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


CREATE TABLE related_products(id BIGINT AUTO_INCREMENT PRIMARY KEY,product_id BIGINT NOT NULL,related_product_id BIGINT NOT NULL,UNIQUE KEY uk_rel_pair(product_id,related_product_id),CONSTRAINT fk_rel_prod FOREIGN KEY(product_id) REFERENCES products(id),CONSTRAINT fk_rel_related FOREIGN KEY(related_product_id) REFERENCES products(id));INSERT INTO categories(name,slug,display_order,is_active) VALUES('Men','men',1,TRUE),('Women','women',2,TRUE),('Kids','kids',3,TRUE);